service: timeline-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}
  environment:
    FIREBASE_SERVICE_ACCOUNT: ${env:FIREBASE_SERVICE_ACCOUNT}
    FIREBASE_API_KEY: ${env:FIREBASE_API_KEY}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}

functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: api/{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline